/**
 * ColorThemeUtils.js
 * 
 * Utility functions and constants for the luma-locked color theme system.
 * The system uses 12 slots with fixed luma (lightness) values.
 * Only hue and saturation are editable per slot.
 */

/**
 * Luma-locked slot definitions.
 * Each slot has a fixed luma value (L in HSL).
 * Organized into 3 clusters (rows): Shadows (1-4), Midtones (5-8), Highlights (9-12)
 * Organized into 4 columns (roles): Secondary 1, Primary, Accent, Secondary 2
 * 
 * Grid layout:
 *                Col 1       Col 2      Col 3       Col 4
 *              Secondary1   Primary    Accent    Secondary2
 * Row 1 (Shadows):   1         2          3          4      (L: 5-25%)
 * Row 2 (Midtones):  5         6          7          8      (L: 35-65%)
 * Row 3 (Highlights):9        10         11         12      (L: 70-97%)
 */
export const LUMA_SLOTS = [
    { slot: 1, luma: 5, cluster: 'shadows', column: 1, role: 'secondary1', label: 'Slot 1' },
    { slot: 2, luma: 10, cluster: 'shadows', column: 2, role: 'primary', label: 'Slot 2' },
    { slot: 3, luma: 18, cluster: 'shadows', column: 3, role: 'accent', label: 'Slot 3' },
    { slot: 4, luma: 25, cluster: 'shadows', column: 4, role: 'secondary2', label: 'Slot 4' },
    { slot: 5, luma: 35, cluster: 'midtones', column: 1, role: 'secondary1', label: 'Slot 5' },
    { slot: 6, luma: 45, cluster: 'midtones', column: 2, role: 'primary', label: 'Slot 6' },
    { slot: 7, luma: 55, cluster: 'midtones', column: 3, role: 'accent', label: 'Slot 7' },
    { slot: 8, luma: 65, cluster: 'midtones', column: 4, role: 'secondary2', label: 'Slot 8' },
    { slot: 9, luma: 70, cluster: 'highlights', column: 1, role: 'secondary1', label: 'Slot 9' },
    { slot: 10, luma: 80, cluster: 'highlights', column: 2, role: 'primary', label: 'Slot 10' },
    { slot: 11, luma: 90, cluster: 'highlights', column: 3, role: 'accent', label: 'Slot 11' },
    { slot: 12, luma: 97, cluster: 'highlights', column: 4, role: 'secondary2', label: 'Slot 12' }
];

/**
 * Column definitions for the 4-column system.
 * Each column has a role and contains 3 slots (one from each tonal row).
 */
export const COLUMN_DEFINITIONS = [
    { column: 1, role: 'secondary1', label: 'Secondary 1', slots: [0, 4, 8] },
    { column: 2, role: 'primary', label: 'Primary', slots: [1, 5, 9] },
    { column: 3, role: 'accent', label: 'Accent', slots: [2, 6, 10] },
    { column: 4, role: 'secondary2', label: 'Secondary 2', slots: [3, 7, 11] }
];

/**
 * Header swatch luma for column editing.
 * Fixed at 50% for neutral midtone preview.
 */
export const COLUMN_HEADER_LUMA = 50;

/**
 * Default adjustment values (photo-style)
 */
export const DEFAULT_ADJUSTMENTS = {
    brightness: 0,      // -100 to +100
    contrast: 0,        // -100 to +100
    highlights: 0,      // -100 to +100
    shadows: 0,         // -100 to +100
    whites: 0,          // -100 to +100
    blacks: 0,          // -100 to +100
    saturation: 0       // -100 to +100
};

/**
 * Minimum perceptible luma difference (Just Noticeable Difference - JND).
 * Research shows ~1-2% luminance difference is the threshold for human perception.
 * We use 2% as a safe minimum to ensure visible distinction between adjacent slots.
 * Weber's Law: ΔL/L ≈ 1-2% for luminance discrimination.
 */
export const MIN_LUMA_DELTA = 2;

/**
 * Quirky theme name vocabulary for generating creative names.
 * Names are generated by combining words from different categories
 * based on the dominant hues and characteristics of the theme.
 */
const THEME_NAME_PARTS = {
    // Hue-based adjectives (mapped to hue ranges)
    hueAdjectives: {
        red: ['Crimson', 'Ruby', 'Scarlet', 'Cherry', 'Vermillion', 'Cardinal', 'Rusty', 'Fiery'],
        orange: ['Amber', 'Tangerine', 'Copper', 'Marmalade', 'Spicy', 'Ginger', 'Pumpkin', 'Peach'],
        yellow: ['Golden', 'Sunny', 'Lemon', 'Honey', 'Mustard', 'Buttery', 'Canary', 'Maize'],
        lime: ['Chartreuse', 'Lime', 'Electric', 'Neon', 'Acid', 'Citrus', 'Zesty', 'Kiwi'],
        green: ['Emerald', 'Forest', 'Jade', 'Mossy', 'Sage', 'Olive', 'Minty', 'Verdant'],
        teal: ['Teal', 'Aqua', 'Lagoon', 'Marine', 'Oceanic', 'Tropical', 'Reef', 'Coastal'],
        cyan: ['Cyan', 'Arctic', 'Glacial', 'Icy', 'Frosty', 'Crystal', 'Azure', 'Polar'],
        blue: ['Cobalt', 'Sapphire', 'Indigo', 'Navy', 'Denim', 'Midnight', 'Royal', 'Steel'],
        purple: ['Violet', 'Lavender', 'Plum', 'Grape', 'Amethyst', 'Orchid', 'Mauve', 'Iris'],
        magenta: ['Magenta', 'Fuchsia', 'Hot', 'Electric', 'Neon', 'Vibrant', 'Bold', 'Vivid'],
        pink: ['Rose', 'Blush', 'Coral', 'Salmon', 'Flamingo', 'Bubblegum', 'Cotton', 'Petal'],
        neutral: ['Smoky', 'Misty', 'Cloudy', 'Dusty', 'Hazy', 'Foggy', 'Ashen', 'Stone']
    },
    // Mood/style nouns
    nouns: [
        'Dreams', 'Whispers', 'Echoes', 'Memories', 'Horizons', 'Shadows', 'Reflections',
        'Twilight', 'Aurora', 'Nebula', 'Cosmos', 'Oasis', 'Mirage', 'Cascade', 'Symphony',
        'Breeze', 'Storm', 'Mist', 'Glow', 'Spark', 'Ember', 'Frost', 'Bloom', 'Drift',
        'Velvet', 'Silk', 'Marble', 'Canvas', 'Prism', 'Essence', 'Spirit', 'Soul',
        'Haven', 'Realm', 'Domain', 'Sphere', 'Aura', 'Vibe', 'Mood', 'Zen'
    ],
    // Intensity modifiers
    intensity: {
        high: ['Vivid', 'Bold', 'Intense', 'Vibrant', 'Electric', 'Dynamic', 'Fierce'],
        medium: ['Gentle', 'Soft', 'Mellow', 'Smooth', 'Calm', 'Serene', 'Balanced'],
        low: ['Muted', 'Subtle', 'Quiet', 'Hushed', 'Faded', 'Pale', 'Whispered']
    },
    // Time/place prefixes
    prefixes: [
        'Midnight', 'Dawn', 'Dusk', 'Twilight', 'Morning', 'Evening', 'Summer', 'Winter',
        'Autumn', 'Spring', 'Urban', 'Coastal', 'Mountain', 'Desert', 'Nordic', 'Tropical',
        'Vintage', 'Modern', 'Retro', 'Neo', 'Abstract', 'Cosmic', 'Ethereal', 'Digital'
    ]
};

/**
 * Get hue category name based on hue value
 * @param {number} hue - Hue value (0-360)
 * @returns {string} Category name
 */
function getHueCategory(hue) {
    if (hue < 15 || hue >= 345) return 'red';
    if (hue < 45) return 'orange';
    if (hue < 75) return 'yellow';
    if (hue < 105) return 'lime';
    if (hue < 150) return 'green';
    if (hue < 180) return 'teal';
    if (hue < 210) return 'cyan';
    if (hue < 255) return 'blue';
    if (hue < 285) return 'purple';
    if (hue < 315) return 'magenta';
    return 'pink';
}

/**
 * Generate a creative theme name based on the theme's colors
 * @param {Array<{h: number, s: number}>} slots - 12 slot colors
 * @returns {string} Generated theme name
 */
export function generateThemeName(slots) {
    // Analyze the theme's dominant characteristics
    const hues = slots.map(s => s.h);
    const saturations = slots.map(s => s.s);
    
    // Get dominant hue (most common hue range)
    const hueCounts = {};
    hues.forEach(h => {
        const cat = getHueCategory(h);
        hueCounts[cat] = (hueCounts[cat] || 0) + 1;
    });
    const dominantHue = Object.entries(hueCounts).sort((a, b) => b[1] - a[1])[0][0];
    
    // Check for secondary hue
    const hueCategories = [...new Set(hues.map(getHueCategory))];
    const secondaryHue = hueCategories.find(h => h !== dominantHue);
    
    // Calculate average saturation for intensity
    const avgSat = saturations.reduce((a, b) => a + b, 0) / saturations.length;
    const intensity = avgSat > 60 ? 'high' : (avgSat > 30 ? 'medium' : 'low');
    
    // Build the name with some randomness for variety
    const parts = THEME_NAME_PARTS;
    const rand = (arr) => arr[Math.floor(Math.random() * arr.length)];
    
    // Different name patterns
    const patterns = [
        // "Crimson Dreams"
        () => `${rand(parts.hueAdjectives[dominantHue] || parts.hueAdjectives.neutral)} ${rand(parts.nouns)}`,
        // "Midnight Amber"
        () => `${rand(parts.prefixes)} ${rand(parts.hueAdjectives[dominantHue] || parts.hueAdjectives.neutral)}`,
        // "Vivid Coral Breeze"
        () => `${rand(parts.intensity[intensity])} ${rand(parts.hueAdjectives[dominantHue] || parts.hueAdjectives.neutral)} ${rand(parts.nouns)}`,
        // "Urban Jade"
        () => `${rand(parts.prefixes)} ${rand(parts.hueAdjectives[dominantHue] || parts.hueAdjectives.neutral)}`,
        // "Emerald & Copper" (if two distinct hues)
        () => secondaryHue ? 
            `${rand(parts.hueAdjectives[dominantHue] || parts.hueAdjectives.neutral)} & ${rand(parts.hueAdjectives[secondaryHue] || parts.hueAdjectives.neutral)}` :
            `${rand(parts.hueAdjectives[dominantHue] || parts.hueAdjectives.neutral)} ${rand(parts.nouns)}`,
        // "Subtle Dusk"
        () => `${rand(parts.intensity[intensity])} ${rand(parts.nouns)}`,
    ];
    
    return rand(patterns)();
}

/**
 * Convert HSL to hex color
 * @param {number} h - Hue (0-360)
 * @param {number} s - Saturation (0-100)
 * @param {number} l - Lightness (0-100)
 * @returns {string} Hex color string
 */
export function hslToHex(h, s, l) {
    s /= 100;
    l /= 100;
    
    const c = (1 - Math.abs(2 * l - 1)) * s;
    const x = c * (1 - Math.abs((h / 60) % 2 - 1));
    const m = l - c / 2;
    
    let r, g, b;
    
    if (h >= 0 && h < 60) {
        [r, g, b] = [c, x, 0];
    } else if (h >= 60 && h < 120) {
        [r, g, b] = [x, c, 0];
    } else if (h >= 120 && h < 180) {
        [r, g, b] = [0, c, x];
    } else if (h >= 180 && h < 240) {
        [r, g, b] = [0, x, c];
    } else if (h >= 240 && h < 300) {
        [r, g, b] = [x, 0, c];
    } else {
        [r, g, b] = [c, 0, x];
    }
    
    const toHex = (n) => {
        const hex = Math.round((n + m) * 255).toString(16);
        return hex.length === 1 ? '0' + hex : hex;
    };
    
    return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

/**
 * Convert hex color to HSL
 * @param {string} hex - Hex color string
 * @returns {{h: number, s: number, l: number}} HSL values
 */
export function hexToHsl(hex) {
    // Remove # if present
    hex = hex.replace(/^#/, '');
    
    // Parse hex
    const r = parseInt(hex.substring(0, 2), 16) / 255;
    const g = parseInt(hex.substring(2, 4), 16) / 255;
    const b = parseInt(hex.substring(4, 6), 16) / 255;
    
    const max = Math.max(r, g, b);
    const min = Math.min(r, g, b);
    let h, s;
    const l = (max + min) / 2;
    
    if (max === min) {
        h = s = 0;
    } else {
        const d = max - min;
        s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
        
        switch (max) {
            case r:
                h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
                break;
            case g:
                h = ((b - r) / d + 2) / 6;
                break;
            case b:
                h = ((r - g) / d + 4) / 6;
                break;
        }
    }
    
    return {
        h: Math.round(h * 360),
        s: Math.round(s * 100),
        l: Math.round(l * 100)
    };
}

/**
 * Determine if a color is dark (for contrast purposes)
 * @param {string} hex - Hex color string
 * @returns {boolean} True if color is dark
 */
export function isColorDark(hex) {
    const { l } = hexToHsl(hex);
    return l < 50;
}

/**
 * Apply brightness adjustment to luma value
 * @param {number} luma - Original luma (0-100)
 * @param {number} brightness - Brightness adjustment (-100 to +100)
 * @returns {number} Adjusted luma
 */
export function applyBrightness(luma, brightness) {
    const adjustment = brightness * 0.5; // Scale factor
    return Math.max(0, Math.min(100, luma + adjustment));
}

/**
 * Apply contrast adjustment to luma value
 * @param {number} luma - Original luma (0-100)
 * @param {number} contrast - Contrast adjustment (-100 to +100)
 * @returns {number} Adjusted luma
 */
export function applyContrast(luma, contrast) {
    const factor = (contrast + 100) / 100;
    const midpoint = 50;
    const adjusted = midpoint + (luma - midpoint) * factor;
    return Math.max(0, Math.min(100, adjusted));
}

/**
 * Apply highlights adjustment (affects high luma values)
 * @param {number} luma - Original luma (0-100)
 * @param {number} highlights - Highlights adjustment (-100 to +100)
 * @returns {number} Adjusted luma
 */
export function applyHighlights(luma, highlights) {
    if (luma < 50) return luma;
    const factor = (luma - 50) / 50; // 0-1 for highlights region
    const adjustment = highlights * 0.3 * factor;
    return Math.max(0, Math.min(100, luma + adjustment));
}

/**
 * Apply shadows adjustment (affects low luma values)
 * @param {number} luma - Original luma (0-100)
 * @param {number} shadows - Shadows adjustment (-100 to +100)
 * @returns {number} Adjusted luma
 */
export function applyShadows(luma, shadows) {
    if (luma > 50) return luma;
    const factor = (50 - luma) / 50; // 0-1 for shadows region
    const adjustment = shadows * 0.3 * factor;
    return Math.max(0, Math.min(100, luma + adjustment));
}

/**
 * Apply whites adjustment (affects very high luma values)
 * @param {number} luma - Original luma (0-100)
 * @param {number} whites - Whites adjustment (-100 to +100)
 * @returns {number} Adjusted luma
 */
export function applyWhites(luma, whites) {
    if (luma < 80) return luma;
    const factor = (luma - 80) / 20; // 0-1 for whites region
    const adjustment = whites * 0.2 * factor;
    return Math.max(0, Math.min(100, luma + adjustment));
}

/**
 * Apply blacks adjustment (affects very low luma values)
 * @param {number} luma - Original luma (0-100)
 * @param {number} blacks - Blacks adjustment (-100 to +100)
 * @returns {number} Adjusted luma
 */
export function applyBlacks(luma, blacks) {
    if (luma > 20) return luma;
    const factor = (20 - luma) / 20; // 0-1 for blacks region
    const adjustment = blacks * 0.2 * factor;
    return Math.max(0, Math.min(100, luma + adjustment));
}

/**
 * Apply saturation adjustment
 * @param {number} saturation - Original saturation (0-100)
 * @param {number} adjustment - Saturation adjustment (-100 to +100)
 * @returns {number} Adjusted saturation
 */
export function applySaturation(saturation, adjustment) {
    const factor = (adjustment + 100) / 100;
    return Math.max(0, Math.min(100, saturation * factor));
}

/**
 * Apply all adjustments to a slot color
 * @param {{h: number, s: number}} slotColor - Slot's hue and saturation
 * @param {number} baseLuma - Slot's fixed luma value
 * @param {Object} adjustments - All adjustment values
 * @returns {{h: number, s: number, l: number}} Adjusted HSL values
 */
export function applyAdjustments(slotColor, baseLuma, adjustments) {
    let luma = baseLuma;
    
    // Apply luma adjustments in order
    luma = applyBrightness(luma, adjustments.brightness);
    luma = applyContrast(luma, adjustments.contrast);
    luma = applyHighlights(luma, adjustments.highlights);
    luma = applyShadows(luma, adjustments.shadows);
    luma = applyWhites(luma, adjustments.whites);
    luma = applyBlacks(luma, adjustments.blacks);
    
    // Apply saturation adjustment
    const saturation = applySaturation(slotColor.s, adjustments.saturation);
    
    return {
        h: slotColor.h,
        s: saturation,
        l: luma
    };
}

/**
 * Generate theme colors from slot data and adjustments
 * @param {Array<{h: number, s: number}>} slots - 12 slot colors (hue, saturation)
 * @param {Object} adjustments - Adjustment values
 * @returns {Array<string>} 12 hex colors
 */
export function generateThemeColors(slots, adjustments = DEFAULT_ADJUSTMENTS) {
    return LUMA_SLOTS.map((lumaSlot, index) => {
        const slotColor = slots[index] || { h: 0, s: 0 };
        const adjusted = applyAdjustments(slotColor, lumaSlot.luma, adjustments);
        return hslToHex(adjusted.h, adjusted.s, adjusted.l);
    });
}

/**
 * Invert theme colors (for light/dark mode toggle)
 * Luma values are inverted: L → (100 - L)
 * @param {Array<{h: number, s: number}>} slots - 12 slot colors
 * @returns {Array<{h: number, s: number}>} Inverted slots (same H/S, inverted L)
 */
export function invertTheme(slots) {
    // Slots themselves don't change (only H and S are stored)
    // The inversion happens in the luma values
    return [...slots];
}

/**
 * Generate inverted theme colors
 * @param {Array<{h: number, s: number}>} slots - 12 slot colors
 * @param {Object} adjustments - Adjustment values
 * @returns {Array<string>} 12 hex colors with inverted luma
 */
export function generateInvertedThemeColors(slots, adjustments = DEFAULT_ADJUSTMENTS) {
    return LUMA_SLOTS.map((lumaSlot, index) => {
        const slotColor = slots[index] || { h: 0, s: 0 };
        const invertedLuma = 100 - lumaSlot.luma;
        const adjusted = applyAdjustments(slotColor, invertedLuma, adjustments);
        return hslToHex(adjusted.h, adjusted.s, adjusted.l);
    });
}

/**
 * Create a neutral (grayscale) theme
 * All slots have 0 saturation
 * @returns {Array<{h: number, s: number}>} 12 neutral slot colors
 */
export function createNeutralTheme() {
    return LUMA_SLOTS.map(() => ({ h: 0, s: 0 }));
}

/**
 * Create a monochromatic theme from a single hue
 * @param {number} hue - Base hue (0-360)
 * @param {number} saturation - Base saturation (0-100)
 * @returns {Array<{h: number, s: number}>} 12 slot colors
 */
export function createMonochromaticTheme(hue, saturation = 50) {
    return LUMA_SLOTS.map((lumaSlot) => {
        // Reduce saturation for extreme luma values
        let adjustedSat = saturation;
        if (lumaSlot.luma < 15 || lumaSlot.luma > 90) {
            adjustedSat = saturation * 0.5;
        } else if (lumaSlot.luma < 25 || lumaSlot.luma > 80) {
            adjustedSat = saturation * 0.75;
        }
        return { h: hue, s: adjustedSat };
    });
}

/**
 * Create a complementary theme from two hues
 * @param {number} hue1 - Primary hue (0-360)
 * @param {number} hue2 - Complementary hue (0-360)
 * @param {number} saturation - Base saturation (0-100)
 * @returns {Array<{h: number, s: number}>} 12 slot colors
 */
export function createComplementaryTheme(hue1, hue2, saturation = 50) {
    return LUMA_SLOTS.map((lumaSlot, index) => {
        // Alternate between hues, with neutral midtones
        const hue = index < 4 ? hue1 : (index >= 8 ? hue2 : hue1);
        
        // Reduce saturation for extreme luma values
        let adjustedSat = saturation;
        if (lumaSlot.luma < 15 || lumaSlot.luma > 90) {
            adjustedSat = saturation * 0.3;
        } else if (lumaSlot.luma < 25 || lumaSlot.luma > 80) {
            adjustedSat = saturation * 0.5;
        }
        
        return { h: hue, s: adjustedSat };
    });
}

/**
 * Color harmony types for theme generation
 */
export const COLOR_HARMONIES = {
    COMPLEMENTARY: 'complementary',
    MONOCHROMATIC: 'monochromatic',
    ANALOGOUS: 'analogous',
    TRIADIC: 'triadic',
    SPLIT_COMPLEMENTARY: 'split-complementary',
    TETRADIC: 'tetradic',
    SQUARE: 'square'
};

/**
 * Generate random hue
 * @returns {number} Random hue (0-360)
 */
export function randomHue() {
    return Math.floor(Math.random() * 360);
}

/**
 * Generate random saturation (biased toward middle values)
 * @returns {number} Random saturation (30-80)
 */
export function randomSaturation() {
    return 30 + Math.floor(Math.random() * 50);
}

/**
 * Slot distribution for generated themes.
 * Maps each slot index to a role: primary, secondary, tertiary, or accent.
 * 
 * Shadows (slots 1-4):  Tertiary, Secondary, Primary, Accent
 * Midtones (slots 5-8): Tertiary, Secondary, Primary, Accent
 * Highlights (slots 9-12): Accent, Primary, Secondary, Tertiary
 */
const SLOT_ROLE_MAP = [
    'tertiary',   // Slot 1 (index 0)
    'secondary',  // Slot 2 (index 1)
    'primary',    // Slot 3 (index 2)
    'accent',     // Slot 4 (index 3)
    'tertiary',   // Slot 5 (index 4)
    'secondary',  // Slot 6 (index 5)
    'primary',    // Slot 7 (index 6)
    'accent',     // Slot 8 (index 7)
    'accent',     // Slot 9 (index 8)
    'primary',    // Slot 10 (index 9)
    'secondary',  // Slot 11 (index 10)
    'tertiary'    // Slot 12 (index 11)
];

/**
 * Generate 4 hues based on color harmony, then randomly assign to roles.
 * @param {string} harmony - Color harmony type
 * @returns {{primary: number, secondary: number, tertiary: number, accent: number}} Hue assignments
 */
function generateHarmonyHues(harmony) {
    const baseHue = randomHue();
    let hues = [];
    
    switch (harmony) {
        case COLOR_HARMONIES.COMPLEMENTARY:
            // 2 hues - we'll derive 4 by adding slight variations
            hues = [
                baseHue,
                (baseHue + 180) % 360,
                (baseHue + 15) % 360,      // Slight variation of base
                (baseHue + 195) % 360      // Slight variation of complement
            ];
            break;
        case COLOR_HARMONIES.MONOCHROMATIC:
            // Single hue for all - use same hue with saturation variations later
            hues = [baseHue, baseHue, baseHue, baseHue];
            break;
        case COLOR_HARMONIES.ANALOGOUS:
            // 3 adjacent hues + one more
            hues = [
                baseHue,
                (baseHue + 30) % 360,
                (baseHue + 330) % 360,     // -30
                (baseHue + 15) % 360       // Between base and +30
            ];
            break;
        case COLOR_HARMONIES.TRIADIC:
            // 3 hues 120° apart + one variation
            hues = [
                baseHue,
                (baseHue + 120) % 360,
                (baseHue + 240) % 360,
                (baseHue + 60) % 360       // Midpoint between base and first
            ];
            break;
        case COLOR_HARMONIES.SPLIT_COMPLEMENTARY:
            // Base + two near-complement hues + one more
            hues = [
                baseHue,
                (baseHue + 150) % 360,
                (baseHue + 210) % 360,
                (baseHue + 180) % 360      // True complement
            ];
            break;
        case COLOR_HARMONIES.TETRADIC:
            // 4 hues in rectangle pattern
            hues = [
                baseHue,
                (baseHue + 60) % 360,
                (baseHue + 180) % 360,
                (baseHue + 240) % 360
            ];
            break;
        case COLOR_HARMONIES.SQUARE:
            // 4 hues 90° apart
            hues = [
                baseHue,
                (baseHue + 90) % 360,
                (baseHue + 180) % 360,
                (baseHue + 270) % 360
            ];
            break;
        default:
            hues = [baseHue, baseHue, baseHue, baseHue];
    }
    
    // Shuffle the 4 hues randomly to assign to roles
    const shuffled = [...hues].sort(() => Math.random() - 0.5);
    
    return {
        primary: shuffled[0],
        secondary: shuffled[1],
        tertiary: shuffled[2],
        accent: shuffled[3]
    };
}

/**
 * Generate theme colors using a specific color harmony
 * @param {string} harmony - Color harmony type
 * @param {Array<number>} lockedSlots - Indices of locked slots (won't be changed)
 * @param {Array<{h: number, s: number}>} existingSlots - Current slot values (for locked slots)
 * @returns {Array<{h: number, s: number}>} 12 slot colors
 */
export function generateHarmonyTheme(harmony, lockedSlots = [], existingSlots = []) {
    const baseSat = randomSaturation();
    
    // Generate 4 hues and randomly assign to Primary, Secondary, Tertiary, Accent
    const roleHues = generateHarmonyHues(harmony);
    
    return LUMA_SLOTS.map((lumaSlot, index) => {
        // Skip locked slots
        if (lockedSlots.includes(index) && existingSlots[index]) {
            return { ...existingSlots[index] };
        }
        
        // Get the role for this slot and its assigned hue
        const role = SLOT_ROLE_MAP[index];
        const hue = roleHues[role];
        
        // Vary saturation based on luma (reduce for very dark/light slots)
        let saturation = baseSat;
        if (lumaSlot.luma < 15 || lumaSlot.luma > 90) {
            saturation = baseSat * 0.3;
        } else if (lumaSlot.luma < 25 || lumaSlot.luma > 80) {
            saturation = baseSat * 0.6;
        }
        
        // Add slight random variation to saturation
        saturation = Math.max(0, Math.min(100, saturation + (Math.random() - 0.5) * 15));
        
        return { h: hue, s: Math.round(saturation) };
    });
}

/**
 * Calculate the effective luma values after applying adjustments.
 * Used to check for clipping and minimum delta constraints.
 * @param {Object} adjustments - Adjustment values
 * @returns {Array<number>} 12 effective luma values
 */
export function calculateEffectiveLumaValues(adjustments) {
    return LUMA_SLOTS.map(lumaSlot => {
        // Apply adjustments to get the effective luma
        const adjusted = applyAdjustments({ h: 0, s: 0 }, lumaSlot.luma, adjustments);
        return adjusted.l;
    });
}

/**
 * Check if adjustments would cause clipping or violate minimum delta.
 * @param {Object} adjustments - Adjustment values to check
 * @returns {{valid: boolean, clipped: boolean, deltaViolation: boolean, minDelta: number}}
 */
export function validateAdjustments(adjustments) {
    const lumaValues = calculateEffectiveLumaValues(adjustments);
    
    // Check for clipping
    const clipped = lumaValues.some(l => l <= 0 || l >= 100);
    
    // Check minimum delta between consecutive slots
    let minDelta = Infinity;
    for (let i = 1; i < lumaValues.length; i++) {
        const delta = Math.abs(lumaValues[i] - lumaValues[i - 1]);
        minDelta = Math.min(minDelta, delta);
    }
    
    const deltaViolation = minDelta < MIN_LUMA_DELTA;
    
    return {
        valid: !clipped && !deltaViolation,
        clipped,
        deltaViolation,
        minDelta
    };
}

/**
 * Generate random adjustments that respect luma constraints.
 * Ensures no clipping and maintains minimum perceptible delta between slots.
 * @param {number} maxAttempts - Maximum attempts to find valid adjustments
 * @returns {Object} Valid random adjustments
 */
export function generateRandomAdjustments(maxAttempts = 50) {
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
        // Generate random adjustments with moderate ranges
        // Use smaller ranges to increase chance of valid results
        const adjustments = {
            brightness: Math.round((Math.random() - 0.5) * 40),   // -20 to +20
            contrast: Math.round((Math.random() - 0.5) * 30),      // -15 to +15
            highlights: Math.round((Math.random() - 0.5) * 50),    // -25 to +25
            shadows: Math.round((Math.random() - 0.5) * 50),       // -25 to +25
            whites: Math.round((Math.random() - 0.5) * 30),        // -15 to +15
            blacks: Math.round((Math.random() - 0.5) * 30),        // -15 to +15
            saturation: Math.round((Math.random() - 0.5) * 60)     // -30 to +30
        };
        
        const validation = validateAdjustments(adjustments);
        if (validation.valid) {
            return adjustments;
        }
    }
    
    // Fallback to default if no valid random found
    return { ...DEFAULT_ADJUSTMENTS };
}

/**
 * Extract theme colors from an image
 * Uses canvas to sample colors and map to luma slots
 * @param {HTMLImageElement} image - Source image
 * @returns {Promise<Array<{h: number, s: number}>>} 12 slot colors
 */
export async function extractThemeFromImage(image) {
    return new Promise((resolve) => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        
        // Sample at reasonable size
        const sampleSize = 100;
        canvas.width = sampleSize;
        canvas.height = sampleSize;
        
        ctx.drawImage(image, 0, 0, sampleSize, sampleSize);
        const imageData = ctx.getImageData(0, 0, sampleSize, sampleSize);
        const pixels = imageData.data;
        
        // Collect all colors with their HSL values
        const colors = [];
        for (let i = 0; i < pixels.length; i += 4) {
            const r = pixels[i];
            const g = pixels[i + 1];
            const b = pixels[i + 2];
            const hex = `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`;
            const hsl = hexToHsl(hex);
            colors.push(hsl);
        }
        
        // Group colors by luma ranges (matching our slots)
        const slots = LUMA_SLOTS.map(lumaSlot => {
            // Find colors within ±10 of slot's luma
            const range = 10;
            const matches = colors.filter(c => 
                Math.abs(c.l - lumaSlot.luma) <= range
            );
            
            if (matches.length === 0) {
                // No matches, find closest
                const sorted = colors.slice().sort((a, b) => 
                    Math.abs(a.l - lumaSlot.luma) - Math.abs(b.l - lumaSlot.luma)
                );
                return { h: sorted[0]?.h || 0, s: sorted[0]?.s || 0 };
            }
            
            // Average the matching colors
            const avgH = Math.round(matches.reduce((sum, c) => sum + c.h, 0) / matches.length);
            const avgS = Math.round(matches.reduce((sum, c) => sum + c.s, 0) / matches.length);
            
            return { h: avgH, s: avgS };
        });
        
        resolve(slots);
    });
}

/**
 * Apply theme colors to CSS variables
 * @param {Array<string>} colors - 12 hex colors
 * @param {HTMLElement} root - Root element (defaults to :root)
 */
export function applyThemeToCSSVariables(colors, root = document.documentElement) {
    colors.forEach((color, index) => {
        root.style.setProperty(`--theme-slot${index + 1}`, color);
    });
}

/**
 * Generate CSS variable declarations for a theme
 * @param {Array<string>} colors - 12 hex colors
 * @returns {string} CSS variable declarations
 */
export function generateThemeCSSVariables(colors) {
    return colors.map((color, index) => 
        `--theme-slot${index + 1}: ${color};`
    ).join('\n');
}

/**
 * Validate theme data structure
 * @param {Object} theme - Theme object to validate
 * @returns {{valid: boolean, errors: string[]}} Validation result
 */
export function validateTheme(theme) {
    const errors = [];
    
    if (!theme) {
        errors.push('Theme is null or undefined');
        return { valid: false, errors };
    }
    
    if (!theme.id || typeof theme.id !== 'string') {
        errors.push('Theme must have a string id');
    }
    
    if (!theme.name || typeof theme.name !== 'string') {
        errors.push('Theme must have a string name');
    }
    
    if (!Array.isArray(theme.slots) || theme.slots.length !== 12) {
        errors.push('Theme must have exactly 12 slots');
    } else {
        theme.slots.forEach((slot, index) => {
            if (typeof slot.h !== 'number' || slot.h < 0 || slot.h > 360) {
                errors.push(`Slot ${index + 1}: hue must be 0-360`);
            }
            if (typeof slot.s !== 'number' || slot.s < 0 || slot.s > 100) {
                errors.push(`Slot ${index + 1}: saturation must be 0-100`);
            }
        });
    }
    
    return { valid: errors.length === 0, errors };
}

/**
 * Create a theme object
 * @param {string} id - Unique identifier
 * @param {string} name - Display name
 * @param {Array<{h: number, s: number}>} slots - 12 slot colors
 * @param {boolean} isPreset - Whether this is a preset theme
 * @returns {Object} Theme object
 */
export function createTheme(id, name, slots, isPreset = false) {
    return {
        id,
        name,
        slots,
        adjustments: { ...DEFAULT_ADJUSTMENTS },
        isPreset,
        createdAt: Date.now(),
        modifiedAt: Date.now()
    };
}

/**
 * Clone a theme with new id
 * @param {Object} theme - Theme to clone
 * @param {string} newId - New unique identifier
 * @param {string} newName - New display name
 * @returns {Object} Cloned theme
 */
export function cloneTheme(theme, newId, newName) {
    return {
        ...theme,
        id: newId,
        name: newName,
        slots: theme.slots.map(slot => ({ ...slot })),
        adjustments: { ...theme.adjustments },
        isPreset: false,
        createdAt: Date.now(),
        modifiedAt: Date.now()
    };
}

/**
 * Generate a unique theme ID
 * @returns {string} Unique ID
 */
export function generateThemeId() {
    return `theme_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Get all slot indices belonging to a column.
 * @param {number} columnIndex - Column index (0-3)
 * @returns {number[]} Array of slot indices
 */
export function getColumnSlots(columnIndex) {
    return COLUMN_DEFINITIONS[columnIndex]?.slots || [];
}

/**
 * Get the column index for a given slot index.
 * @param {number} slotIndex - Slot index (0-11)
 * @returns {number} Column index (0-3)
 */
export function getSlotColumn(slotIndex) {
    return slotIndex % 4;
}

/**
 * Get the row (cluster) index for a given slot index.
 * @param {number} slotIndex - Slot index (0-11)
 * @returns {number} Row index (0-2): 0=shadows, 1=midtones, 2=highlights
 */
export function getSlotRow(slotIndex) {
    return Math.floor(slotIndex / 4);
}

/**
 * Update all slots in a column to share the same hue and saturation.
 * @param {Array<{h: number, s: number}>} slots - Current slot array
 * @param {number} columnIndex - Column index (0-3)
 * @param {number} hue - New hue value (0-360)
 * @param {number} saturation - New saturation value (0-100)
 * @returns {Array<{h: number, s: number}>} Updated slots array
 */
export function updateColumnHue(slots, columnIndex, hue, saturation) {
    const columnSlots = getColumnSlots(columnIndex);
    return slots.map((slot, index) => {
        if (columnSlots.includes(index)) {
            return { h: hue, s: saturation };
        }
        return { ...slot };
    });
}

/**
 * Get the hue and saturation for a column from the first slot in that column.
 * All slots in a column share the same hue/saturation.
 * @param {Array<{h: number, s: number}>} slots - Slot array
 * @param {number} columnIndex - Column index (0-3)
 * @returns {{h: number, s: number}} Hue and saturation
 */
export function getColumnHueSaturation(slots, columnIndex) {
    const columnSlots = getColumnSlots(columnIndex);
    const firstSlotIndex = columnSlots[0];
    return slots[firstSlotIndex] || { h: 0, s: 0 };
}

/**
 * Generate a hex color for a column header swatch (displayed at 60% luma).
 * @param {Array<{h: number, s: number}>} slots - Slot array
 * @param {number} columnIndex - Column index (0-3)
 * @returns {string} Hex color
 */
export function getColumnHeaderColor(slots, columnIndex) {
    const { h, s } = getColumnHueSaturation(slots, columnIndex);
    return hslToHex(h, s, COLUMN_HEADER_LUMA);
}

/**
 * Generate column hues for the 4-column system based on color harmony.
 * Returns 4 hues, one for each column role.
 * @param {string} harmony - Color harmony type
 * @returns {{secondary1: number, primary: number, accent: number, secondary2: number}}
 */
export function generateColumnHarmonyHues(harmony) {
    const baseHue = randomHue();
    let hues = [];
    
    switch (harmony) {
        case COLOR_HARMONIES.COMPLEMENTARY:
            // Secondary1 and Primary share base, Accent and Secondary2 share complement
            hues = [baseHue, baseHue, (baseHue + 180) % 360, (baseHue + 180) % 360];
            break;
        case COLOR_HARMONIES.MONOCHROMATIC:
            hues = [baseHue, baseHue, baseHue, baseHue];
            break;
        case COLOR_HARMONIES.ANALOGOUS:
            // Adjacent hues on wheel
            hues = [
                (baseHue + 330) % 360,  // -30
                baseHue,                 // base
                (baseHue + 30) % 360,   // +30
                (baseHue + 15) % 360    // +15
            ];
            break;
        case COLOR_HARMONIES.TRIADIC:
            // 3 hues + one fill
            hues = [
                baseHue,
                (baseHue + 120) % 360,
                (baseHue + 240) % 360,
                (baseHue + 60) % 360
            ];
            break;
        case COLOR_HARMONIES.SPLIT_COMPLEMENTARY:
            hues = [
                baseHue,
                baseHue,
                (baseHue + 150) % 360,
                (baseHue + 210) % 360
            ];
            break;
        case COLOR_HARMONIES.TETRADIC:
            hues = [
                baseHue,
                (baseHue + 60) % 360,
                (baseHue + 180) % 360,
                (baseHue + 240) % 360
            ];
            break;
        case COLOR_HARMONIES.SQUARE:
            hues = [
                baseHue,
                (baseHue + 90) % 360,
                (baseHue + 180) % 360,
                (baseHue + 270) % 360
            ];
            break;
        default:
            hues = [baseHue, baseHue, baseHue, baseHue];
    }
    
    return {
        secondary1: hues[0],
        primary: hues[1],
        accent: hues[2],
        secondary2: hues[3]
    };
}

/**
 * Generate theme colors using the 4-column system.
 * All slots in a column share the same hue.
 * Saturation is randomized with all 4 columns within a 30-point window.
 * @param {string} harmony - Color harmony type
 * @param {Array<number>} lockedColumns - Indices of locked columns (won't be changed)
 * @param {Array<{h: number, s: number}>} existingSlots - Current slot values (for locked columns)
 * @returns {Array<{h: number, s: number}>} 12 slot colors
 */
export function generateColumnHarmonyTheme(harmony, lockedColumns = [], existingSlots = []) {
    const columnHues = generateColumnHarmonyHues(harmony);
    
    // Generate saturation with a 30-point window that can slide through 0-100 range
    // The window base can be 0-70 (so max saturation in window is 100)
    const satWindowBase = Math.floor(Math.random() * 71); // 0-70
    const satWindowEnd = satWindowBase + 30; // 30-100
    
    // Generate 4 random saturations within this 30-point window
    const baseSaturations = {
        secondary1: satWindowBase + Math.floor(Math.random() * 31),
        primary: satWindowBase + Math.floor(Math.random() * 31),
        accent: satWindowBase + Math.floor(Math.random() * 31),
        secondary2: satWindowBase + Math.floor(Math.random() * 31)
    };
    
    return LUMA_SLOTS.map((lumaSlot, index) => {
        const columnIndex = getSlotColumn(index);
        
        // Skip locked columns
        if (lockedColumns.includes(columnIndex) && existingSlots[index]) {
            return { ...existingSlots[index] };
        }
        
        const role = lumaSlot.role;
        const hue = columnHues[role];
        let saturation = baseSaturations[role];
        
        // Reduce saturation for extreme luma values
        if (lumaSlot.luma < 15 || lumaSlot.luma > 90) {
            saturation = saturation * 0.4;
        } else if (lumaSlot.luma < 25 || lumaSlot.luma > 80) {
            saturation = saturation * 0.7;
        }
        
        return { h: hue, s: Math.round(saturation) };
    });
}
